# Generated by Django 4.2.5 on 2024-03-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_partner_active_job'),
        ('job_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassignment',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.partner'),
        ),
    ]
