# Generated by Django 4.2.5 on 2024-03-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0002_alter_jobassignment_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignment',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
