# Generated by Django 4.2.5 on 2024-04-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_partner_active_job'),
        ('job_management', '0003_jobassignment_finished_at_jobassignment_is_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='media/')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Seller')),
                ('tax_identification_number', models.CharField(blank=True, max_length=100, verbose_name='Tax Identification Number')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Invoice Number')),
                ('date_of_issue', models.DateTimeField(blank=True, null=True, verbose_name='Date of Issue')),
                ('place_of_issue', models.CharField(blank=True, max_length=100, verbose_name='Place of Issue')),
                ('buyer', models.CharField(blank=True, max_length=100, verbose_name='Place of Issue')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total')),
                ('iban', models.CharField(blank=True, max_length=100, verbose_name='iban')),
                ('payment_status', models.CharField(blank=True, choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=100, null=True, verbose_name='Payment Status')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'cash'), ('bank_transfer', 'bank_transfer'), ('blik', 'blik')], max_length=100, null=True, verbose_name='Payment Method')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.partner')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, verbose_name='Item')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Price')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Subtotal')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='job_management.invoice')),
            ],
        ),
    ]
