# Generated by Django 4.2.5 on 2024-03-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_delete_jobassignment'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='active_job',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.job'),
        ),
    ]
