version: 2.23.3
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend:/app/
    environment:
      DJANGO_SETTINGS_MODULE: workshop.settings_prod
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_HOST: POSTGRES_HOST
    env_file: .env

    ports:
      - "8000:8000"
    image: app:django

    restart: on-failure

  db:
    image: postgres:12
    env_file: .env
    volumes:
      - ./db:/db
    environment:
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_HOST: POSTGRES_HOST2


  nginx:
    build: ./nginx
    restart: on-failure
    ports:
      [ 80:80 ]
    volumes:
    - ./nginx:/nginx
    depends_on:
      - app



