# Generated by Django 3.2.13 on 2022-09-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service',
            field=models.TextField(blank=True),
        ),
    ]
