# Generated by Django 4.2.5 on 2023-11-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=15)),
                ('production_year', models.SmallIntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('engine_displacement', models.SmallIntegerField()),
                ('transmission', models.CharField(max_length=20)),
                ('horsepower', models.SmallIntegerField()),
                ('service', models.TextField(blank=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.make')),
            ],
        ),
    ]
