# Generated by Django 4.2.5 on 2024-02-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=9)),
                ('adress', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('body_type', models.CharField(max_length=20)),
                ('production_year', models.SmallIntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('engine_displacement', models.SmallIntegerField()),
                ('transmission', models.CharField(max_length=20)),
                ('horsepower', models.SmallIntegerField()),
                ('service', models.TextField(blank=True)),
            ],
        ),
    ]
