# Generated by Django 4.2.5 on 2024-02-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('booking', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.job')),
                ('mechanic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.partner')),
            ],
        ),
    ]
