# Generated by Django 4.2.5 on 2024-02-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_jobassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobAssignment',
        ),
    ]
