# Generated by Django 4.2.5 on 2024-03-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_delete_jobassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='engine_displacement',
            field=models.FloatField(),
        ),
    ]
